# Generated by Django 4.2.2 on 2023-09-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8, unique=True)),
                ('location', models.CharField(max_length=8)),
                ('company', models.CharField(max_length=15)),
            ],
        ),
    ]
